exports.employees = [
    { name: 'Ashik', value: .40 },
    { name: 'Edi Amin', value: .21 },
    { name: 'Farazi', value: .05 },
    { name: 'Hasinur', value: .32 },
    { name: 'Ibnul Kayes', value: .30 },
    { name: 'Jayonto Sarkar', value: .12 },
    { name: 'Mahabub', value: .30 },
    { name: 'Mamun', value: .10 },
    { name: 'Mishu', value: .25 },
    { name: 'Nadim', value: .16 },
    { name: 'Rokibul Alam', value: .23 },
    { name: 'Rokibul Islam', value: .30 },
    { name: 'Sabbir', value: -.25 },
    { name: 'Saimon', value: .02 },
    { name: 'Shaikat', value: .35 },
    { name: 'Sourov', value: .10 },
    { name: 'Tanmay', value: .04 },
    { name: 'Towhid', value: .19 }
]


exports.replaceTypes = [
    { searchString: 'Bug', replaceString: 'Bug Fixed'},
    { searchString: 'Bug Fix', replaceString: 'Bug Fixed'},
    { searchString: 'Bug Fixes', replaceString: 'Bug Fixed'},
    { searchString: 'Bux Fix', replaceString: 'Bug Fixed'},
    { searchString: 'Other', replaceString: 'Others'},
    { searchString: 'Manual Testing & Discussion', replaceString: 'Testing'},
    { searchString: 'Automation', replaceString: 'Testing'},
    { searchString: 'Automation Testing', replaceString: 'Testing'},
    { searchString: 'Discussion & Meeting', replaceString: 'Meeting'},
    { searchString: 'Discussion & Manual Testing', replaceString: 'Testing'},
    { searchString: 'Manual Testing', replaceString: 'Testing'},
    { searchString: 'Testing & Release', replaceString: 'Testing'},
    { searchString: 'Update', replaceString: 'Enhancement'},
    { searchString: 'Refactor', replaceString: 'Enhancement'},
    { searchString: 'Manual & Automation', replaceString: 'Testing'},
    { searchString: 'Setup', replaceString: 'Others'},
    { searchString: 'Improvement', replaceString: 'Enhancement'},
    { searchString: 'Checking', replaceString: 'Testing'},
    { searchString: 'Writting Test Scenario', replaceString: 'Testing'},
    { searchString: 'Milestone Set', replaceString: 'Others'},
    { searchString: 'Discussion', replaceString: 'Meeting'},
    { searchString: 'Change Log', replaceString: 'Others'},
    { searchString: 'Project Manage', replaceString: 'Others'},
    { searchString: 'Support', replaceString: 'Others'},
]


exports.replaceProjects = [
    { searchString: 'WE POS', replaceString: 'POS'},
    { searchString: 'Dokan Pro', replaceString: 'Dokan'},
    { searchString: 'Dokan Free', replaceString: 'Dokan'},
    { searchString: 'PM Free', replaceString: 'Project Manager'},
    { searchString: 'PM Pro', replaceString: 'Project Manager'},
    { searchString: 'WPUF Pro', replaceString: 'WPUF'},
    { searchString: 'Dokan App Plugin', replaceString: 'Dokan App'},
    { searchString: 'ERP Attendance', replaceString: 'ERP'},
    { searchString: 'ERP HR Training', replaceString: 'ERP'},
    { searchString: 'ERP Demo Site', replaceString: 'ERP'},
    { searchString: 'ERP Document Manager', replaceString: 'ERP'},
    { searchString: 'ERP HR Training', replaceString: 'ERP'},
    { searchString: 'ERP Recruitment', replaceString: 'ERP'},
    { searchString: 'ERP Zendesk', replaceString: 'ERP'},
    { searchString: 'ERP-Attendance', replaceString: 'ERP'},
    { searchString: 'ERP-Site', replaceString: 'ERP'},
    { searchString: 'weForms Pro', replaceString: 'weForms'},
    { searchString: 'weForms/weForms Pro', replaceString: 'weForms'},
    { searchString: 'wePOS', replaceString: 'POS'},
    { searchString: 'woocommerce conversion tracking', replaceString: 'WCCT'},
    { searchString: 'power-block', replaceString: 'Power Blocks'},
    { searchString: 'power blocks', replaceString: 'Power Blocks'},
    { searchString: 'WC Conversion Tracking', replaceString: 'WCCT'},
    { searchString: 'WP ERP', replaceString: 'ERP'},
    { searchString: 'ERP-Demo-Client', replaceString: 'ERP'},
    { searchString: 'WP User Frontend', replaceString: 'WPUF'},
]